### ISSUE TITLE
reuploaded bpk is not reuploaded to local cache

### ISSUE THREAD

**Issue by donarus** [ever-been/everBeen#106]
If is bpk present in local cache, reuload to the software repository does not cause refresh in the local cache cache. This is unexpected behavior.

**Comment by sixtam** [comment]
imho, this is expected behavior. There could/should be an option to disable/clear local caches.

**Comment by radek-macha** [comment]
Re-upload is not supposed to be supported at all. We left it in for convenience purposes, but overwriting an existing version of a BPK is considered an invalid operation. The BPK developer is supposed to change the BPK's version before re-uploading.

**Comment by donarus** [comment]
And what about this ... User deletes BPK from repository and uploads the same BPK (with same name/group/version) from another machine, where old BPK is cached .. what is expected behavior?

**Comment by radek-macha** [comment]
I think one thing needs clarifying. What do you mean by 'the same'?

I'll say it again:
- uploading the same (groupId, artifactId, version) BPK twice is not legal, because the BPKs whose identifier matches exactly are supposed to also have exactly the same content
- therefore, deleting the BPK is not a strictly supported operation; it will have to be possible for the sake of clearing some space in the repository, but no guarantees are made in terms of cache state

**Comment by donarus** [comment]
I totally disagree.
  If user have the possibility (either supported or not) to delete BPKs, I totally disagree that reuploading BPK is an invalid operation. We should allow it or we should strictly forbid delete operation otherwise.

**_But I do not think that it is correct to prohibit delete/reupload.**_

So my idea is to use simple CRC hash code (built and cached on SR startup/SRClient startup) or cached somewhere in '.persistence' folder used by SR/SR client and updated on each download/upload BPK (very rare operation in context of other BEEN operations). And then compare client/server CRC in each 'download bpk' request.
- In case that BPK is cached locally and codes are equal, use local version.
- In case that BPK is cached locally and codes are NOT equal, delete local version and download new version.
- In case that BPK is NOT cached locally, use server version

This should be really cheap to implement and the effect will be very positive for the potential user.

I could implement this behavior.

**Comment by donarus** [comment]
NOTE:

This is from meeting protocol from meeting with J.Tauber
`2012/08/29+31, 09:00 ... JT shared with us experience with using maven(!there should be word 'BEEN'!) in production environment. 
.
.
One task cannot be run multiple times. We need to increase version and lod it again into repository.
The most reliable way to restart cache is restart been
.
.`

**Comment by radek-macha** [comment]
As opposed to you, I do believe it incorrect to allow delete/reupload. If it comes to tracking history and user delete/re-upload is allowed, we have no way of guaranteeing that the user code that produced some behavior/results is still the same.
It also breaks the semantics of uniquely identified code (same identifier, same code).
I think of deletes from the software repository in the same way as of deletes from logs - they only get deleted when they become obsolete and no longer interesting.
I'm not arguing the fact that it would be cheap/easy to implement what you're proposing. I am merely convinced that it is not right to do so and that your time would be better spent on other issues. I am also curious about why do you need deletes from the repository so bad. If there's any reason, please provide it.
As for JT's remarks: From what I recall, the main objection was the necessity to change the version id in multiple config files. As for the necessity of changing software version when the software itself changes, I am convinced that it is a necessary evil (at least in production environment).
Earlier on, we talked about been-provided auto-versioning to remedy this, so it might be interesting to think about this.
Finally, if this issue comes to us having different opinions, it might be wiser to save the debate for later when we can decide collectively.

**Comment by sixtam** [comment]
I agree with @radek-macha. For the sake of debugging we could support SNAPSHOTs as in Maven: if the version is "whatever-version-SNAPSHOT" download it every time from the central store.

**Comment by donarus** [comment]
I agree with Martin's ( @sixtam ) solution with addition that it should be possible to invoke 'empty cache of all currently live host runtimes...' from web interface (for example after SR cleanup cleanup)

**Comment by radek-macha** [comment]
Yes, that sounds good.

As for cache clearing, I recommend creating a SoftwareStore extension (SoftwareCache) featuring a clear() method, extending the fsbasedstore implementation to SoftwareCache but maintaining use of the SoftwareStore interface in the SR service.

**Comment by donarus** [comment]
ack... I'm ready to start coding :coffee: :1234: :coffee: :1234: :coffee:

**Comment by andrejpodzimek** [comment]
As far as cache consistency issues are concerned... One solution might be a "paused mode" in BEEN (a quiescent state when no tasks actively run and all planned analyses are postponed till the end of that state). The envisioned workflow:
- The admin asks BEEN to reach a quiescent state (which might take a considerable amout of time)
- BEEN notifies the admin (anyhow, that doesn't matter) that a quiescent state has been reached
- The admin is allowed to do all the dirty tricks one might think of (which would otherwise break cache consistency, versioning etc.); fixing annoying glitches in naming/versioning could be a possible intention
- The admin resumes BEEN with the new state and all the dirty operations are banned again, i.e., bpks can't change under the tasks' hands etc.

This would give the user some kind of a "dirty flexibility", but it would still preserve all the reasonable guarantees (such as same id / same code) during normal operation.

Because I have no idea whether this is hard to implement (or implementable at all), just feel free to ignore this suggestion. :-) Such a feature would be definitely hard to debug and test...

**Comment by donarus** [comment]
Closed as NOT A BUG.

We can implement special page (and/or API), where user specify what he wants to delete (results? bpks? logs?) and 'WE' decide what else will be deleted. The reason is simple: CONSISTENCY of SR and RR (and data in HC cluster too).

Example:
- User wants to delete BPK
- There are results for the deleted BPK -> inconsistency -> All results of tasks/task contexts/benchmarks specified in this BPK should be deleted
- There are unusable BPKs -> inconsistency -> All BPKs for which is the deleted BPK dependency should be deleted too.
