### ISSUE TITLE
Cannot compile bcmd on Mac OS X - signals

### ISSUE THREAD

**Issue by kubamracek** [ever-been/everBeen#40]
Compiling bcmd on Mac OS X fails with the following message:

```
[INFO] /bin/sh -c cd /Users/newacc/Documents/everBeen/bcmd && gcc -std=c99 -O2 -pipe -Wall -pedantic -I/Users/newacc/Documents/everBeen/bcmd/unix -o/Users/newacc/Documents/everBeen/bcmd/target/objs/bcmd.o -c /Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c
/Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c: In function ‘set_sig’:
/Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c:953: error: ‘SIGPWR’ undeclared (first use in this function)
/Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c:953: error: (Each undeclared identifier is reported only once
/Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c:953: error: for each function it appears in.)
/Users/newacc/Documents/everBeen/bcmd/unix/bcmd.c:953: error: ‘SIGWINCH’ undeclared (first use in this function)
```

The signals SIGPWR, SIGWINCH are not available on Mac OS X.

**Comment by andrejpodzimek** [comment]
This probably means that OS X doesn't implement / support these signals. Please feel free to remove them from the array of signals for which signal dispositions are changed, as a quick workaround. (line 953)

In the long run, some #ifdef could be added. BTW, signals for which SIG_IGN is the default behavior can be removed from the array anyway (SIGWINCH...), since ignored signals do not interrupt system calls and setting the SA_RESTART flag for them explicitly does not make sense. The comment says it all:

```
/**
 * Sets SIGPIPE to be ignored. Sets the SA_RESTART flag on it.
 * Furthermore, the SA_RESTART flag is set on all signals that are normally ignored by default.
 * This is not necessary and will be removed later. Only SIGPIPE matters.
 *
 * @return SUCCESS or an error code from result_enum when appropriate.
 */
```

In the long run, it might be nice to set proper signal handlers for some important signals, so that bcmd can report that it received them (possibly based on some debugging / verbose flags).

A summary of current signals:
- `SIGPWR` is rare and cannot be masked / ignored on some platforms...
- `SIGWINCH` is ignored by default and would only make sense for Midnight Commander or X applications, but in those cases a library handles this for you...
- `SIGURG` is something rare ... it might occur on BSDs and their descendants, but is ignored by default.
- `SIGCHLD` can _never_ be obtained by bcmd, since it doesn't fork and thus doesn't have any children. On some systems you can send this signal explicitly (you can't do it in AIX, for instance), but why would anyone do that...? And it's ignored anyway.

**Comment by sixtam** [comment]
As both signals are ignored by default (on platforms where specified) i think the whole function can be simplified by removing the code which sets the SA_RESTART flag.

**Comment by andrejpodzimek** [comment]
...or just removed temporarily (so that it builds) and redesigned later for proper reporting of unexpected signals through some debugging messages...
