### ISSUE TITLE
Review basic Software Repository

### ISSUE THREAD

**Issue by radek-macha** [ever-been/everBeen#76]
Review of #68

Review concerns following projects:
- software-repository
- software-repository-store
- software-repository-fsbasedstore
- software-repository-client

**Comment by sixtam** [comment]
SoftwareRepository.stop() function seems not to work.

**Comment by sixtam** [comment]
Low priority:
Starting the SoftwareRepository should fail when appropriate(#start() throwing an exception?). I get "Unable to bind server socket on port 8000 - Address already in use" but no Exception (and yes the address is in use).

**Comment by sixtam** [comment]
Here are my findings:

MAJOR
SwRepository.stop() does not work because it is blocked in
    socket = serverSocket.accept();
which seems to ignore interrupts -> set timeout to the socket.

MINOR
There is unused (duplicated)  cz.cuni.mff.d3s.been.swrepository.HttpServerException

NORMAL
FSBasedStore should be parametrized with FS_ROOT_NAME 

NORMAL
FSBasedStore#init() is not actually used
